use_frameworks!

platform :ios, '9.0'

target 'MAPageViewController_Example' do
  pod 'MAPageViewController', :path => '../'

  target 'MAPageViewController_Tests' do
    inherit! :search_paths

    
  end
end
